export const SpecLibraryDummyData = [
  {
    uuid: "1",
    marker: "Title",
    relativeIndex: 0,
    type: "title",
    content: "test default value",
    subList: null,
  },
  {
    uuid: "2",
    marker: "Subtitle",
    relativeIndex: 1,
    type: "subTitle",
    content: "test default value",
    subList: null,
  },
  {
    uuid: "3",
    marker: "List",
    relativeIndex: 2,
    type: "list",
    content: null,
    subList: [
      {
        uuid: "4",
        marker: "PART 1.",
        relativeIndex: 0,
        type: "partHeading",
        content: "test default value",
        subList: [
          {
            uuid: "5",
            marker: "1.1",
            relativeIndex: 0,
            type: "sectionHeading",
            content: "test default value",
            subList: [
              {
                uuid: "6",
                marker: "A.",
                relativeIndex: 0,
                type: "subsection",
                content: "test default value",
                subList: [
                  {
                    uuid: "7",
                    marker: "1.",
                    relativeIndex: 0,
                    type: "subsectionList",
                    content: "test default value",
                    subList: null,
                  },
                  {
                    uuid: "12",
                    marker: "2.",
                    relativeIndex: 1,
                    type: "subsectionList",
                    content: "test default value",
                    subList: [
                      {
                        uuid: "30",
                        marker: "a.",
                        relativeIndex: 0,
                        type: "subsectionListDetails",
                        content: "test default value",
                        subList: [
                          {
                            uuid: "29",
                            marker: "1)",
                            relativeIndex: 0,
                            type: "subSubsectionListDetails",
                            content: "test default value",
                            subList: null,
                          },
                        ],
                      },
                      // {
                      //   uuid: "28",
                      //   marker: "b.",
                      //   relativeIndex: 1,
                      //   type: "subsectionListDetails",
                      //   content: "test default value",
                      //   subList: [
                      //     {
                      //       uuid: "27",
                      //       marker: "1)",
                      //       relativeIndex: 0,
                      //       type: "subSubsectionListDetails",
                      //       content: "test default value",
                      //       subList: null,
                      //     },
                      //     {
                      //       uuid: "26",
                      //       marker: "2)",
                      //       relativeIndex: 1,
                      //       type: "subSubsectionListDetails",
                      //       content: "test default value",
                      //       subList: null,
                      //     },
                      //   ],
                      // },
                    ],
                  },
                ],
              },
              {
                uuid: "13",
                marker: "B.",
                relativeIndex: 1,
                type: "subsection",
                content: "test default value",
                subList: null,
              },
            ],
          },
          {
            uuid: "14",
            marker: "1.2",
            relativeIndex: 1,
            type: "sectionHeading",
            content: "test default value",
            subList: null,
          },
        ],
      },
      {
        uuid: "15",
        marker: "PART 2.",
        relativeIndex: 1,
        type: "partHeading",
        content: "test default value test",
        subList: [
          {
            uuid: "16",
            marker: "2.1",
            relativeIndex: 0,
            type: "sectionHeading",
            content: "test default value testtest",
            subList: null,
          },
        ],
      },
      {
        uuid: "17",
        marker: "PART 3.",
        relativeIndex: 2,
        type: "partHeading",
        content: "test default value",
        subList: [
          {
            uuid: "18",
            marker: "3.1",
            relativeIndex: 0,
            type: "sectionHeading",
            content: "test default value",
            subList: null,
          },
          {
            uuid: "20",
            marker: "3.2",
            relativeIndex: 1,
            type: "sectionHeading",
            content: "test default value",
            subList: null,
          },
        ],
      },
    ],
  },
  {
    uuid: "19",
    marker: "End Of Section",
    relativeIndex: 3,
    type: "endOfSection",
    content: "endOfSection test default value",
    subList: null,
  },
];
